# Generated by Django 3.0.4 on 2020-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200328_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
