# Generated by Django 3.0.4 on 2020-03-28 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_organization_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
