# Generated by Django 3.0.4 on 2020-04-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='thumbnail',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
