# Generated by Django 3.0.4 on 2020-05-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200416_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/article/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/quiz/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/video/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
